---
- name: 새로운 사용자 삭제
  hosts: all
  become: true
  remote_user: ansible
  vars_files:
    - secret2.yml
  tasks:
  - name: 사용자 추가 및 암호 설정
    user:
      name: "{{ username }}"
      state: absent
      remove: yes
      