---
# 파일 배포
# (ansible) custom.fact - 배포 -> (web1) /etc/ansible/facts.d/custom.fact
- name: 사용자 정의 팩트 파일 배포하기
  hosts: webserver
  gather_facts: no
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: 폴더 만들기
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: 파일 배포 하기
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
