---
- name: 각 데이터 센터 시간 동기화
  hosts: datacenters
  tasks:
    - name: 타임존 설정
      timezone:
        name: Asia/Seoul
      notify: restart_chronyd

  handlers:
    - name: restart_chronyd
      service:
        name: chronyd
        state: restarted

