---
# Web Server Configuration
# * 1) Install packages
#     # yum -y install httpd mod_ssl
# * 2) Web Server settings
#     # scp files/index.html ansible#:/var/www/html/index/html
# * 3) Web service startup
#     # systemctl enable --now httpd
# * 4) firewall registration
#     # firewall-cmd --permanent --add-service={http,httpd}
# * 5) (?) SELinux

- name: Install and start Apache HTTPD
  hosts: webservers
  tasks:
    - name: Install packages
      yum:
        name: 
          - httpd
          - mod_ssl
        state: present

    - name: Web server settings
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    - name: Web service startup
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Firewall registration - http
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
        
    - name: Firewall registration - https
      firewalld:
        service: https
        permanent: true
        immediate: true
        state: enabled


