---
# 웹 서버 및 DB 서버 설정 복원
- name: 웹 서버 및 DB 서버 설정 복원
  hosts: [webservers]
  tasks:
# 1) "방화벽 서비스 OFF - http, https, mysql" => firewalld
  - name: "방화벽 서비스 OFF - http, https, mysql"
    firewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: disabled
    loop:
      - http
      - https
      - mysql
# 2) "서비스 disable - httpd, mariadb" => service
  - name: "서비스 disable - httpd, mariadb"
    service:
      name: "{{ item }}"
      enabled: no
      state: stopped
    loop:
      - httpd
      - mariadb
    ignore_errors: yes
# 3) "서비스 디렉토리 삭제 - /var/www/html" => file
  - name: "서비스 디렉토리 삭제 - /var/www/html"
    file:
      path: /var/www/html
      state: absent
# 4) "패키지 삭제" => yum|dnf
  - name: "패키지 삭제"
    yum:
      name:
        - httpd
        - mod_ssl
        - php
        - php-mysqlnd
        - php-pdo
        - mariadb
        - mariadb-server
        - python3-pip
      state: absent