---
- name: 역할 설치
  hosts: webservers
  gather_facts: yes
  become: true
  pre_tasks:
  - name: install the gcc
    yum: 
      name: 
      - gcc
      - make
      state: latest

  roles:
  - davidkarban.git